from ophyd import (
    Device,
    Component as Cpt,
    DynamicDeviceComponent as DDC,
    EpicsSignal,
    EpicsSignalRO,
)
from ophyd.areadetector.plugins import (
    PluginBase,
    Overlay,
    ColorConvPlugin,
    FilePlugin,
    HDF5Plugin,
    ImagePlugin,
    JPEGPlugin,
    MagickPlugin,
    NetCDFPlugin,
    NexusPlugin,
    OverlayPlugin,
    ProcessPlugin,
    ROIPlugin,
    StatsPlugin,
    TIFFPlugin,
    TransformPlugin,
)
from ophyd.areadetector import ADBase, EpicsSignalWithRBV as SignalWithRBV, ad_group
from all_plugins import *


class OverlayPlugin_V20(OverlayPlugin, PluginBase_V20, version=(2, 0)):
    overlay_1 = Cpt(Overlay, "1:")
    overlay_2 = Cpt(Overlay, "2:")
    overlay_3 = Cpt(Overlay, "3:")
    overlay_4 = Cpt(Overlay, "4:")
    overlay_5 = Cpt(Overlay, "5:")
    overlay_6 = Cpt(Overlay, "6:")
    overlay_7 = Cpt(Overlay, "7:")
    overlay_8 = Cpt(Overlay, "8:")


class OverlayPlugin_V21(OverlayPlugin, version=(2, 1)):
    overlay_1 = Cpt(Overlay_V21, "1:")
    overlay_2 = Cpt(Overlay_V21, "2:")
    overlay_3 = Cpt(Overlay_V21, "3:")
    overlay_4 = Cpt(Overlay_V21, "4:")
    overlay_5 = Cpt(Overlay_V21, "5:")
    overlay_6 = Cpt(Overlay_V21, "6:")
    overlay_7 = Cpt(Overlay_V21, "7:")
    overlay_8 = Cpt(Overlay_V21, "8:")


class OverlayPlugin_V26(OverlayPlugin, version=(2, 1)):
    overlay_1 = Cpt(Overlay_V26, "1:")
    overlay_2 = Cpt(Overlay_V26, "2:")
    overlay_3 = Cpt(Overlay_V26, "3:")
    overlay_4 = Cpt(Overlay_V26, "4:")
    overlay_5 = Cpt(Overlay_V26, "5:")
    overlay_6 = Cpt(Overlay_V26, "6:")
    overlay_7 = Cpt(Overlay_V26, "7:")
    overlay_8 = Cpt(Overlay_V26, "8:")


class OverlayPlugin_V31(OverlayPlugin, version=(3, 1)):
    overlay_1 = Cpt(Overlay_V31, "1:")
    overlay_2 = Cpt(Overlay_V31, "2:")
    overlay_3 = Cpt(Overlay_V31, "3:")
    overlay_4 = Cpt(Overlay_V31, "4:")
    overlay_5 = Cpt(Overlay_V31, "5:")
    overlay_6 = Cpt(Overlay_V31, "6:")
    overlay_7 = Cpt(Overlay_V31, "7:")
    overlay_8 = Cpt(Overlay_V31, "8:")


class CommonPlugins(ADBase):
    ...


class CommonPlugins_V20(CommonPlugins, version=(2, 0)):
    cc1 = Cpt(ColorConvPlugin, "CC1:")
    cc2 = Cpt(ColorConvPlugin, "CC2:")
    hdf1 = Cpt(HDF5Plugin_V20, "HDF1:")
    jpeg1 = Cpt(JPEGPlugin_V20, "JPEG1:")
    magick1 = Cpt(MagickPlugin_V20, "Magick1:")
    nexus1 = Cpt(NexusPlugin_V20, "Nexus1:")
    over1 = Cpt(OverlayPlugin_V20, "Over1:")
    proc1 = Cpt(ProcessPlugin, "Proc1:")
    roi1 = Cpt(ROIPlugin, "ROI1:")
    roi2 = Cpt(ROIPlugin, "ROI2:")
    roi3 = Cpt(ROIPlugin, "ROI3:")
    roi4 = Cpt(ROIPlugin, "ROI4:")
    stats1 = Cpt(StatsPlugin, "Stats1:")
    stats2 = Cpt(StatsPlugin, "Stats2:")
    stats3 = Cpt(StatsPlugin, "Stats3:")
    stats4 = Cpt(StatsPlugin, "Stats4:")
    stats5 = Cpt(StatsPlugin, "Stats5:")
    tiff1 = Cpt(TIFFPlugin_V20, "TIFF1:")
    trans1 = Cpt(TransformPlugin, "Trans1:")
    netcdf1 = Cpt(NetCDFPlugin_V20, "netCDF1:")


class CommonPlugins_V21(CommonPlugins, version=(2, 1)):
    cc1 = Cpt(ColorConvPlugin, "CC1:")
    cc2 = Cpt(ColorConvPlugin, "CC2:")
    hdf1 = Cpt(HDF5Plugin_V21, "HDF1:")
    jpeg1 = Cpt(JPEGPlugin_V21, "JPEG1:")
    magick1 = Cpt(MagickPlugin_V21, "Magick1:")
    nexus1 = Cpt(NexusPlugin_V21, "Nexus1:")
    over1 = Cpt(OverlayPlugin_V21, "Over1:")
    proc1 = Cpt(ProcessPlugin, "Proc1:")
    roi1 = Cpt(ROIPlugin, "ROI1:")
    roi2 = Cpt(ROIPlugin, "ROI2:")
    roi3 = Cpt(ROIPlugin, "ROI3:")
    roi4 = Cpt(ROIPlugin, "ROI4:")
    stats1 = Cpt(StatsPlugin, "Stats1:")
    stats2 = Cpt(StatsPlugin, "Stats2:")
    stats3 = Cpt(StatsPlugin, "Stats3:")
    stats4 = Cpt(StatsPlugin, "Stats4:")
    stats5 = Cpt(StatsPlugin, "Stats5:")
    tiff1 = Cpt(TIFFPlugin_V21, "TIFF1:")
    trans1 = Cpt(TransformPlugin_V21, "Trans1:")
    netcdf1 = Cpt(NetCDFPlugin_V21, "netCDF1:")


class CommonPlugins_V22(CommonPlugins, version=(2, 2)):
    attr1 = Cpt(AttributeNPlugin_V22, "Attr1:")
    cb1 = Cpt(CircularBuffPlugin_V22, "CB1:")
    cc1 = Cpt(ColorConvPlugin, "CC1:")
    cc2 = Cpt(ColorConvPlugin, "CC2:")
    hdf1 = Cpt(HDF5Plugin_V22, "HDF1:")
    jpeg1 = Cpt(JPEGPlugin_V22, "JPEG1:")
    magick1 = Cpt(MagickPlugin_V22, "Magick1:")
    nexus1 = Cpt(NexusPlugin_V22, "Nexus1:")
    over1 = Cpt(OverlayPlugin_V21, "Over1:")
    proc1 = Cpt(ProcessPlugin, "Proc1:")
    roi1 = Cpt(ROIPlugin, "ROI1:")
    roi2 = Cpt(ROIPlugin, "ROI2:")
    roi3 = Cpt(ROIPlugin, "ROI3:")
    roi4 = Cpt(ROIPlugin, "ROI4:")
    roistat1 = Cpt(ROIStatPlugin_V22, "ROIStat1:")
    stats1 = Cpt(StatsPlugin_V22, "Stats1:")
    stats2 = Cpt(StatsPlugin_V22, "Stats2:")
    stats3 = Cpt(StatsPlugin_V22, "Stats3:")
    stats4 = Cpt(StatsPlugin_V22, "Stats4:")
    stats5 = Cpt(StatsPlugin_V22, "Stats5:")
    tiff1 = Cpt(TIFFPlugin_V22, "TIFF1:")
    trans1 = Cpt(TransformPlugin_V21, "Trans1:")
    netcdf1 = Cpt(NetCDFPlugin_V22, "netCDF1:")


class CommonPlugins_V23(CommonPlugins, version=(2, 3)):
    attr1 = Cpt(AttributeNPlugin_V22, "Attr1:")
    cb1 = Cpt(CircularBuffPlugin_V22, "CB1:")
    cc1 = Cpt(ColorConvPlugin, "CC1:")
    cc2 = Cpt(ColorConvPlugin, "CC2:")
    hdf1 = Cpt(HDF5Plugin_V22, "HDF1:")
    jpeg1 = Cpt(JPEGPlugin_V22, "JPEG1:")
    magick1 = Cpt(MagickPlugin_V22, "Magick1:")
    nexus1 = Cpt(NexusPlugin_V22, "Nexus1:")
    over1 = Cpt(OverlayPlugin_V21, "Over1:")
    proc1 = Cpt(ProcessPlugin, "Proc1:")
    roi1 = Cpt(ROIPlugin, "ROI1:")
    roi2 = Cpt(ROIPlugin, "ROI2:")
    roi3 = Cpt(ROIPlugin, "ROI3:")
    roi4 = Cpt(ROIPlugin, "ROI4:")
    roistat1 = Cpt(ROIStatPlugin_V23, "ROIStat1:")
    stats1 = Cpt(StatsPlugin_V22, "Stats1:")
    stats2 = Cpt(StatsPlugin_V22, "Stats2:")
    stats3 = Cpt(StatsPlugin_V22, "Stats3:")
    stats4 = Cpt(StatsPlugin_V22, "Stats4:")
    stats5 = Cpt(StatsPlugin_V22, "Stats5:")
    tiff1 = Cpt(TIFFPlugin_V22, "TIFF1:")
    trans1 = Cpt(TransformPlugin_V21, "Trans1:")
    netcdf1 = Cpt(NetCDFPlugin_V22, "netCDF1:")


class CommonPlugins_V24(CommonPlugins, version=(2, 4)):
    attr1 = Cpt(AttributeNPlugin_V22, "Attr1:")
    cb1 = Cpt(CircularBuffPlugin_V22, "CB1:")
    cc1 = Cpt(ColorConvPlugin, "CC1:")
    cc2 = Cpt(ColorConvPlugin, "CC2:")
    hdf1 = Cpt(HDF5Plugin_V22, "HDF1:")
    jpeg1 = Cpt(JPEGPlugin_V22, "JPEG1:")
    magick1 = Cpt(MagickPlugin_V22, "Magick1:")
    nexus1 = Cpt(NexusPlugin_V22, "Nexus1:")
    over1 = Cpt(OverlayPlugin_V21, "Over1:")
    proc1 = Cpt(ProcessPlugin, "Proc1:")
    roi1 = Cpt(ROIPlugin, "ROI1:")
    roi2 = Cpt(ROIPlugin, "ROI2:")
    roi3 = Cpt(ROIPlugin, "ROI3:")
    roi4 = Cpt(ROIPlugin, "ROI4:")
    roistat1 = Cpt(ROIStatPlugin_V23, "ROIStat1:")
    stats1 = Cpt(StatsPlugin_V22, "Stats1:")
    stats2 = Cpt(StatsPlugin_V22, "Stats2:")
    stats3 = Cpt(StatsPlugin_V22, "Stats3:")
    stats4 = Cpt(StatsPlugin_V22, "Stats4:")
    stats5 = Cpt(StatsPlugin_V22, "Stats5:")
    tiff1 = Cpt(TIFFPlugin_V22, "TIFF1:")
    trans1 = Cpt(TransformPlugin_V21, "Trans1:")
    netcdf1 = Cpt(NetCDFPlugin_V22, "netCDF1:")


class CommonPlugins_V25(CommonPlugins, version=(2, 5)):
    attr1 = Cpt(AttributeNPlugin_V22, "Attr1:")
    cb1 = Cpt(CircularBuffPlugin_V22, "CB1:")
    cc1 = Cpt(ColorConvPlugin, "CC1:")
    cc2 = Cpt(ColorConvPlugin, "CC2:")
    hdf1 = Cpt(HDF5Plugin_V25, "HDF1:")
    jpeg1 = Cpt(JPEGPlugin_V22, "JPEG1:")
    magick1 = Cpt(MagickPlugin_V22, "Magick1:")
    nexus1 = Cpt(NexusPlugin_V22, "Nexus1:")
    over1 = Cpt(OverlayPlugin_V21, "Over1:")
    proc1 = Cpt(ProcessPlugin, "Proc1:")
    roi1 = Cpt(ROIPlugin, "ROI1:")
    roi2 = Cpt(ROIPlugin, "ROI2:")
    roi3 = Cpt(ROIPlugin, "ROI3:")
    roi4 = Cpt(ROIPlugin, "ROI4:")
    roistat1 = Cpt(ROIStatPlugin_V23, "ROIStat1:")
    stats1 = Cpt(StatsPlugin_V25, "Stats1:")
    stats2 = Cpt(StatsPlugin_V25, "Stats2:")
    stats3 = Cpt(StatsPlugin_V25, "Stats3:")
    stats4 = Cpt(StatsPlugin_V25, "Stats4:")
    stats5 = Cpt(StatsPlugin_V25, "Stats5:")
    tiff1 = Cpt(TIFFPlugin_V22, "TIFF1:")
    trans1 = Cpt(TransformPlugin_V21, "Trans1:")
    netcdf1 = Cpt(NetCDFPlugin_V22, "netCDF1:")


class CommonPlugins_V26(CommonPlugins, version=(2, 6)):
    attr1 = Cpt(AttributeNPlugin_V22, "Attr1:")
    cb1 = Cpt(CircularBuffPlugin_V22, "CB1:")
    cc1 = Cpt(ColorConvPlugin, "CC1:")
    cc2 = Cpt(ColorConvPlugin, "CC2:")
    hdf1 = Cpt(HDF5Plugin_V25, "HDF1:")
    jpeg1 = Cpt(JPEGPlugin_V22, "JPEG1:")
    magick1 = Cpt(MagickPlugin_V22, "Magick1:")
    nexus1 = Cpt(NexusPlugin_V22, "Nexus1:")
    over1 = Cpt(OverlayPlugin_V26, "Over1:")
    proc1 = Cpt(ProcessPlugin, "Proc1:")
    roi1 = Cpt(ROIPlugin_V26, "ROI1:")
    roi2 = Cpt(ROIPlugin_V26, "ROI2:")
    roi3 = Cpt(ROIPlugin_V26, "ROI3:")
    roi4 = Cpt(ROIPlugin_V26, "ROI4:")
    roistat1 = Cpt(ROIStatPlugin_V23, "ROIStat1:")
    stats1 = Cpt(StatsPlugin_V26, "Stats1:")
    stats2 = Cpt(StatsPlugin_V26, "Stats2:")
    stats3 = Cpt(StatsPlugin_V26, "Stats3:")
    stats4 = Cpt(StatsPlugin_V26, "Stats4:")
    stats5 = Cpt(StatsPlugin_V26, "Stats5:")
    tiff1 = Cpt(TIFFPlugin_V22, "TIFF1:")
    trans1 = Cpt(TransformPlugin_V21, "Trans1:")
    netcdf1 = Cpt(NetCDFPlugin_V22, "netCDF1:")


class CommonPlugins_V31(CommonPlugins, version=(3, 1)):
    attr1 = Cpt(AttributeNPlugin_V22, "Attr1:")
    cb1 = Cpt(CircularBuffPlugin_V22, "CB1:")
    cc1 = Cpt(ColorConvPlugin, "CC1:")
    cc2 = Cpt(ColorConvPlugin, "CC2:")
    fft1 = Cpt(FFTPlugin_V25, "FFT1:")
    gather1 = Cpt(GatherPlugin_V31, "Gather1:")
    hdf1 = Cpt(HDF5Plugin_V25, "HDF1:")
    jpeg1 = Cpt(JPEGPlugin_V22, "JPEG1:")
    nexus1 = Cpt(NexusPlugin_V22, "Nexus1:")
    over1 = Cpt(OverlayPlugin_V31, "Over1:")
    proc1 = Cpt(ProcessPlugin, "Proc1:")
    roi1 = Cpt(ROIPlugin_V26, "ROI1:")
    roi2 = Cpt(ROIPlugin_V26, "ROI2:")
    roi3 = Cpt(ROIPlugin_V26, "ROI3:")
    roi4 = Cpt(ROIPlugin_V26, "ROI4:")
    roistat1 = Cpt(ROIStatPlugin_V23, "ROIStat1:")
    scatter1 = Cpt(ScatterPlugin_V31, "Scatter1:")
    stats1 = Cpt(StatsPlugin_V26, "Stats1:")
    stats2 = Cpt(StatsPlugin_V26, "Stats2:")
    stats3 = Cpt(StatsPlugin_V26, "Stats3:")
    stats4 = Cpt(StatsPlugin_V26, "Stats4:")
    stats5 = Cpt(StatsPlugin_V26, "Stats5:")
    tiff1 = Cpt(TIFFPlugin_V22, "TIFF1:")
    trans1 = Cpt(TransformPlugin_V21, "Trans1:")
    netcdf1 = Cpt(NetCDFPlugin_V22, "netCDF1:")


class CommonPlugins_V32(CommonPlugins, version=(3, 2)):
    attr1 = Cpt(AttributeNPlugin_V22, "Attr1:")
    cb1 = Cpt(CircularBuffPlugin_V22, "CB1:")
    cc1 = Cpt(ColorConvPlugin, "CC1:")
    cc2 = Cpt(ColorConvPlugin, "CC2:")
    fft1 = Cpt(FFTPlugin_V25, "FFT1:")
    gather1 = Cpt(GatherPlugin_V31, "Gather1:")
    hdf1 = Cpt(HDF5Plugin_V32, "HDF1:")
    jpeg1 = Cpt(JPEGPlugin_V22, "JPEG1:")
    nexus1 = Cpt(NexusPlugin_V22, "Nexus1:")
    over1 = Cpt(OverlayPlugin_V31, "Over1:")
    proc1 = Cpt(ProcessPlugin, "Proc1:")
    roi1 = Cpt(ROIPlugin_V26, "ROI1:")
    roi2 = Cpt(ROIPlugin_V26, "ROI2:")
    roi3 = Cpt(ROIPlugin_V26, "ROI3:")
    roi4 = Cpt(ROIPlugin_V26, "ROI4:")
    roistat1 = Cpt(ROIStatPlugin_V23, "ROIStat1:")
    scatter1 = Cpt(ScatterPlugin_V32, "Scatter1:")
    stats1 = Cpt(StatsPlugin_V32, "Stats1:")
    stats2 = Cpt(StatsPlugin_V32, "Stats2:")
    stats3 = Cpt(StatsPlugin_V32, "Stats3:")
    stats4 = Cpt(StatsPlugin_V32, "Stats4:")
    stats5 = Cpt(StatsPlugin_V32, "Stats5:")
    tiff1 = Cpt(TIFFPlugin_V22, "TIFF1:")
    trans1 = Cpt(TransformPlugin_V21, "Trans1:")
    netcdf1 = Cpt(NetCDFPlugin_V22, "netCDF1:")


class CommonPlugins_V33(CommonPlugins, version=(3, 3)):
    attr1 = Cpt(AttributeNPlugin_V22, "Attr1:")
    cb1 = Cpt(CircularBuffPlugin_V22, "CB1:")
    cc1 = Cpt(ColorConvPlugin, "CC1:")
    cc2 = Cpt(ColorConvPlugin, "CC2:")
    fft1 = Cpt(FFTPlugin_V25, "FFT1:")
    gather1 = Cpt(GatherPlugin_V31, "Gather1:")
    hdf1 = Cpt(HDF5Plugin_V32, "HDF1:")
    jpeg1 = Cpt(JPEGPlugin_V22, "JPEG1:")
    nexus1 = Cpt(NexusPlugin_V22, "Nexus1:")
    over1 = Cpt(OverlayPlugin_V31, "Over1:")
    proc1 = Cpt(ProcessPlugin_V33, "Proc1:")
    roi1 = Cpt(ROIPlugin_V26, "ROI1:")
    roi2 = Cpt(ROIPlugin_V26, "ROI2:")
    roi3 = Cpt(ROIPlugin_V26, "ROI3:")
    roi4 = Cpt(ROIPlugin_V26, "ROI4:")
    roistat1 = Cpt(ROIStatPlugin_V23, "ROIStat1:")
    scatter1 = Cpt(ScatterPlugin_V32, "Scatter1:")
    stats1 = Cpt(StatsPlugin_V33, "Stats1:")
    stats2 = Cpt(StatsPlugin_V33, "Stats2:")
    stats3 = Cpt(StatsPlugin_V33, "Stats3:")
    stats4 = Cpt(StatsPlugin_V33, "Stats4:")
    stats5 = Cpt(StatsPlugin_V33, "Stats5:")
    tiff1 = Cpt(TIFFPlugin_V22, "TIFF1:")
    trans1 = Cpt(TransformPlugin_V21, "Trans1:")
    netcdf1 = Cpt(NetCDFPlugin_V22, "netCDF1:")


class CommonPlugins_V331(CommonPlugins, version=(3, 3, 1)):
    attr1 = Cpt(AttributeNPlugin_V22, "Attr1:")
    cb1 = Cpt(CircularBuffPlugin_V22, "CB1:")
    cc1 = Cpt(ColorConvPlugin, "CC1:")
    cc2 = Cpt(ColorConvPlugin, "CC2:")
    fft1 = Cpt(FFTPlugin_V25, "FFT1:")
    gather1 = Cpt(GatherPlugin_V31, "Gather1:")
    hdf1 = Cpt(HDF5Plugin_V32, "HDF1:")
    jpeg1 = Cpt(JPEGPlugin_V22, "JPEG1:")
    nexus1 = Cpt(NexusPlugin_V22, "Nexus1:")
    over1 = Cpt(OverlayPlugin_V31, "Over1:")
    proc1 = Cpt(ProcessPlugin_V33, "Proc1:")
    roi1 = Cpt(ROIPlugin_V26, "ROI1:")
    roi2 = Cpt(ROIPlugin_V26, "ROI2:")
    roi3 = Cpt(ROIPlugin_V26, "ROI3:")
    roi4 = Cpt(ROIPlugin_V26, "ROI4:")
    roistat1 = Cpt(ROIStatPlugin_V23, "ROIStat1:")
    scatter1 = Cpt(ScatterPlugin_V32, "Scatter1:")
    stats1 = Cpt(StatsPlugin_V33, "Stats1:")
    stats2 = Cpt(StatsPlugin_V33, "Stats2:")
    stats3 = Cpt(StatsPlugin_V33, "Stats3:")
    stats4 = Cpt(StatsPlugin_V33, "Stats4:")
    stats5 = Cpt(StatsPlugin_V33, "Stats5:")
    tiff1 = Cpt(TIFFPlugin_V22, "TIFF1:")
    trans1 = Cpt(TransformPlugin_V21, "Trans1:")
    netcdf1 = Cpt(NetCDFPlugin_V22, "netCDF1:")


class CommonPlugins_V332(CommonPlugins, version=(3, 3, 2)):
    attr1 = Cpt(AttributeNPlugin_V22, "Attr1:")
    cb1 = Cpt(CircularBuffPlugin_V22, "CB1:")
    cc1 = Cpt(ColorConvPlugin, "CC1:")
    cc2 = Cpt(ColorConvPlugin, "CC2:")
    fft1 = Cpt(FFTPlugin_V25, "FFT1:")
    gather1 = Cpt(GatherPlugin_V31, "Gather1:")
    hdf1 = Cpt(HDF5Plugin_V32, "HDF1:")
    jpeg1 = Cpt(JPEGPlugin_V22, "JPEG1:")
    nexus1 = Cpt(NexusPlugin_V22, "Nexus1:")
    over1 = Cpt(OverlayPlugin_V31, "Over1:")
    proc1 = Cpt(ProcessPlugin_V33, "Proc1:")
    roi1 = Cpt(ROIPlugin_V26, "ROI1:")
    roi2 = Cpt(ROIPlugin_V26, "ROI2:")
    roi3 = Cpt(ROIPlugin_V26, "ROI3:")
    roi4 = Cpt(ROIPlugin_V26, "ROI4:")
    roistat1 = Cpt(ROIStatPlugin_V23, "ROIStat1:")
    scatter1 = Cpt(ScatterPlugin_V32, "Scatter1:")
    stats1 = Cpt(StatsPlugin_V33, "Stats1:")
    stats2 = Cpt(StatsPlugin_V33, "Stats2:")
    stats3 = Cpt(StatsPlugin_V33, "Stats3:")
    stats4 = Cpt(StatsPlugin_V33, "Stats4:")
    stats5 = Cpt(StatsPlugin_V33, "Stats5:")
    tiff1 = Cpt(TIFFPlugin_V22, "TIFF1:")
    trans1 = Cpt(TransformPlugin_V21, "Trans1:")
    netcdf1 = Cpt(NetCDFPlugin_V22, "netCDF1:")


class CommonPlugins_V34(CommonPlugins, version=(3, 4)):
    attr1 = Cpt(AttributeNPlugin_V22, "Attr1:")
    cb1 = Cpt(CircularBuffPlugin_V34, "CB1:")
    cc1 = Cpt(ColorConvPlugin, "CC1:")
    cc2 = Cpt(ColorConvPlugin, "CC2:")
    codec1 = Cpt(CodecPlugin_V34, "Codec1:")
    codec2 = Cpt(CodecPlugin_V34, "Codec2:")
    fft1 = Cpt(FFTPlugin_V25, "FFT1:")
    gather1 = Cpt(GatherPlugin_V31, "Gather1:")
    hdf1 = Cpt(HDF5Plugin_V32, "HDF1:")
    jpeg1 = Cpt(JPEGPlugin_V22, "JPEG1:")
    nexus1 = Cpt(NexusPlugin_V22, "Nexus1:")
    over1 = Cpt(OverlayPlugin_V31, "Over1:")
    proc1 = Cpt(ProcessPlugin_V33, "Proc1:")
    roi1 = Cpt(ROIPlugin_V26, "ROI1:")
    roi2 = Cpt(ROIPlugin_V26, "ROI2:")
    roi3 = Cpt(ROIPlugin_V26, "ROI3:")
    roi4 = Cpt(ROIPlugin_V26, "ROI4:")
    roistat1 = Cpt(ROIStatPlugin_V23, "ROIStat1:")
    scatter1 = Cpt(ScatterPlugin_V32, "Scatter1:")
    stats1 = Cpt(StatsPlugin_V33, "Stats1:")
    stats2 = Cpt(StatsPlugin_V33, "Stats2:")
    stats3 = Cpt(StatsPlugin_V33, "Stats3:")
    stats4 = Cpt(StatsPlugin_V33, "Stats4:")
    stats5 = Cpt(StatsPlugin_V33, "Stats5:")
    tiff1 = Cpt(TIFFPlugin_V22, "TIFF1:")
    trans1 = Cpt(TransformPlugin_V21, "Trans1:")
    netcdf1 = Cpt(NetCDFPlugin_V22, "netCDF1:")
